### ISSUE TITLE
router:debug returns an exception

### ISSUE THREAD

**Issue by zebba** [WouterJ/Bundleless#5]
Running php app/console router:debug does not work as expected:

```
 [Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                             
  Warning: strpos(): Empty needle in /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php line 94
```

I narrowed down the issue to ControllerNameParser::build(). The $controller parameter is resolved to:

```
web_profiler.controller.profiler:toolbarAction
...
web_profiler.controller.exception:showAction
...
Sensio\Bundle\DistributionBundle\Controller\ConfiguratorController::checkAction
...
\Controller\Report\Api\TemplateController::indexAction
```

The last controller is located in src/Controller/Report/Api/TemplateController.php

I was not able to narrow it down any further however, since I can't seem to find the line where build() is actually called from.

**Comment by wouterj** [comment]
This is indeed a problem when using the empty namespace option. As this line:

```
if (0 !== strpos($className, $bundle->getNamespace())) {
```

Will then trigger this error (the second parameter of strpos cannot be empty).

The solution would be to use an `App\` namespace for your application. This is also what I would recommend (I'll change the default of this lib sometime), as this will avoid name conflicts.
